language: node_js
sudo: false
node_js:
- '10.16.0'
install:
- yarn install
before_script:
- VERBOSE=1 ./bin/cli.js check
script:
- yarn test
- VERBOSE=1 ./bin/cli.js bump
after_success:
- VERBOSE=1 ./bin/cli.js publish
